// scripts/generate-google-fonts.ts
//
// Fetches the public Google Fonts metadata endpoint (no API key required),
// strips the anti-JSON-hijacking junk prefix, and writes a fully typed
// registry to src/lib/generated/google-fonts.ts.
//
// Run with:  node scripts/generate-google-fonts.ts
//
// Node 24 strips TS types natively, so this file must avoid enums / namespaces /
// decorators / parameter properties. Use plain JS + erasable type annotations only.

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const META_URL = 'https://fonts.google.com/metadata/fonts';
const OUT_PATH = resolve(
	dirname(fileURLToPath(import.meta.url)),
	'../src/lib/generated/google-fonts.ts'
);

type Category = 'sans' | 'serif' | 'mono';

interface FontMeta {
	category: Category;
	axes: { tag: string; min: number; max: number }[];
	weights: number[];
	subsets: string[];
	variable: boolean;
}

// Google category string -> our normalized category union.
function mapCategory(googleCategory: string): Category {
	switch (googleCategory) {
		case 'Monospace':
			return 'mono';
		case 'Serif':
			return 'serif';
		case 'Sans Serif':
			return 'sans';
		// Display / Handwriting / anything unknown -> sans (default)
		default:
			return 'sans';
	}
}

// ~40 popular families used when the network fetch fails, so the generated
// file always exists and typechecks.
const SEED: Record<string, Category> = {
	Inter: 'sans',
	Roboto: 'sans',
	'Open Sans': 'sans',
	Lato: 'sans',
	Montserrat: 'sans',
	Poppins: 'sans',
	'Noto Sans': 'sans',
	Raleway: 'sans',
	'Work Sans': 'sans',
	Nunito: 'sans',
	'Nunito Sans': 'sans',
	'PT Sans': 'sans',
	Rubik: 'sans',
	Mulish: 'sans',
	'DM Sans': 'sans',
	Manrope: 'sans',
	Karla: 'sans',
	'Fira Sans': 'sans',
	Quicksand: 'sans',
	Oswald: 'sans',
	'Source Sans 3': 'sans',
	Ubuntu: 'sans',
	Heebo: 'sans',
	'Roboto Mono': 'mono',
	'JetBrains Mono': 'mono',
	'Fira Code': 'mono',
	'Source Code Pro': 'mono',
	'IBM Plex Mono': 'mono',
	'Space Mono': 'mono',
	Inconsolata: 'mono',
	'Ubuntu Mono': 'mono',
	Merriweather: 'serif',
	'Playfair Display': 'serif',
	Lora: 'serif',
	'PT Serif': 'serif',
	'Noto Serif': 'serif',
	'Source Serif 4': 'serif',
	'Libre Baskerville': 'serif',
	'Crimson Text': 'serif',
	'EB Garamond': 'serif',
	Bitter: 'serif'
};

function seedRegistry(): Record<string, FontMeta> {
	const out: Record<string, FontMeta> = {};
	for (const [family, category] of Object.entries(SEED)) {
		out[family] = {
			category,
			axes: [],
			weights: [400, 700],
			subsets: ['latin'],
			variable: false
		};
	}
	return out;
}

async function fetchRegistry(): Promise<Record<string, FontMeta>> {
	const res = await fetch(META_URL);
	if (!res.ok) throw new Error(`metadata endpoint returned ${res.status}`);
	const raw = await res.text();
	// Strip the anti-hijacking junk prefix before the first '{'.
	const start = raw.indexOf('{');
	if (start < 0) throw new Error('no JSON object found in metadata response');
	const data = JSON.parse(raw.slice(start)) as {
		familyMetadataList: Array<{
			family: string;
			category: string;
			axes?: { tag: string; min: number; max: number; defaultValue?: number }[];
			fonts?: Record<string, unknown>;
			subsets?: string[];
		}>;
	};

	const out: Record<string, FontMeta> = {};
	for (const f of data.familyMetadataList) {
		const axes = (f.axes ?? []).map((a) => ({ tag: a.tag, min: a.min, max: a.max }));
		// Weights come from the `fonts` map keys (e.g. "400", "700", "400i").
		const weights = Array.from(
			new Set(
				Object.keys(f.fonts ?? {})
					.map((k) => parseInt(k, 10))
					.filter((n) => Number.isFinite(n))
			)
		).sort((a, b) => a - b);
		out[f.family] = {
			category: mapCategory(f.category),
			axes,
			weights: weights.length ? weights : [400],
			subsets: f.subsets ?? ['latin'],
			// Variable if a weight axis ("wght") is present.
			variable: axes.some((a) => a.tag === 'wght')
		};
	}
	return out;
}

function emit(registry: Record<string, FontMeta>): string {
	const names = Object.keys(registry).sort((a, b) => a.localeCompare(b));
	const union = names.map((n) => `\t| ${JSON.stringify(n)}`).join('\n');
	const entries = names
		.map((n) => `\t${JSON.stringify(n)}: ${JSON.stringify(registry[n])}`)
		.join(',\n');
	const nameList = names.map((n) => `\t${JSON.stringify(n)}`).join(',\n');

	return `// AUTO-GENERATED by scripts/generate-google-fonts.ts — DO NOT EDIT.
// Regenerate with: node scripts/generate-google-fonts.ts

export type GoogleFontName =
${union};

export interface GoogleFontMeta {
	category: 'sans' | 'serif' | 'mono';
	axes: { tag: string; min: number; max: number }[];
	weights: number[];
	subsets: string[];
	variable: boolean;
}

export const googleFonts: Record<GoogleFontName, GoogleFontMeta> = {
${entries}
};

export const GOOGLE_FONT_NAMES: GoogleFontName[] = [
${nameList}
];
`;
}

async function main(): Promise<void> {
	let registry: Record<string, FontMeta>;
	try {
		registry = await fetchRegistry();
		console.log(
			`[generate-google-fonts] OK: fetched ${Object.keys(registry).length} families from ${META_URL}`
		);
	} catch (err) {
		registry = seedRegistry();
		console.warn(
			`[generate-google-fonts] FETCH FAILED (${(err as Error).message}); using hardcoded seed of ${Object.keys(registry).length} families`
		);
	}
	await mkdir(dirname(OUT_PATH), { recursive: true });
	await writeFile(OUT_PATH, emit(registry), 'utf8');
	console.log(`[generate-google-fonts] wrote ${OUT_PATH}`);
}

main().catch((err) => {
	console.error('[generate-google-fonts] FATAL', err);
	process.exit(1);
});
